### PR TITLE
Design Footer

### PR DESCRIPTION
**Pull request by riskycase**
Added a starting design that's in sync with the chosen theme, but I have a doubt if we'd move forward with a black and white design

### CODE REVIEW

**Comment by Bisht13** [comment]
Hey @riskycase can you squash the commits?

**Comment by ykarim** [comment]
Hi @riskycase , this seems good but here's some comments:

* The back to top seems pointless. Users could simply scroll if they really want to. It's not really common to include this
* You're missing the mobile design
* Since the Contact page is now renamed to Help can you reflect this?
* Also, what color is the background? It should flow with the rest of the page

**Comment by riskycase** [comment]
Hey @ykarim , these are the changes I made according to your points


> * The back to top seems pointless. Users could simply scroll if they really want to. It's not really common to include this

I'm planning to leave it there for the convenience of the user
> * You're missing the mobile design
> * Since the Contact page is now renamed to Help can you reflect this?

Added both the changes
> * Also, what color is the background? It should flow with the rest of the page

I had made it opaque black according to the design but on second thoughts I've set it to 204 alpha value

**Comment by ykarim** [comment]
This is all good, but for the mobile design that might not fit on all screens (some phones are still small screen sizes). What do you think about having a vertically displayed set of links similar to how [Square](squareup.com) or [Lyft](lyft.com) are designed for mobile

**Comment by riskycase** [comment]
Adding both list of links to a single column would make the footer too tall on mobile so I moved the img-links a bit closer to center and lower to try reducing the width. Besides I also tweaked the design a bit like using an opaque dark gray instead of transperant black and increasing padding between heading and links in the columns

**Comment by ykarim** [comment]
Resolves #32

**Pull request merged**
